title: A Raspberry Pi laser tripwire
hero_image: images/banner.png
description: Build a laser tripwire with Python and a Raspberry Pi
original_url: https://www.raspberrypi.org/learning/laser-tripwire/
theme: cc-prototype
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: developer, design-1, programming-2, phys-comp-3, manufacture-0, community-0
interests: "jokes"
technologies: "raspberry-pi, python, physical computing"
steps:
  - title: Introduction
  - title: What you will need
  - title: Detecting a broken beam
  - title: Making some noise
  - title: Building your laser tripwire
  - title: What next?
